spring.application.name=auth-security
server.port=8080
spring.main.web-application-type=reactive
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest1



# JWT config
#jwt.secret=${JWT_SECRET}
#jwt.expiration=36000000  # 10 hours
#jwt.secret=hQZVZj3L2I5MpqjP/Apns5M2xFjjkBfPTX1X34U0zYI=

spring.data.mongodb.uri=mongodb://localhost:27017/payment-services
spring.data.mongodb.database=payment-services
spring.data.mongodb.port=27017
spring.data.mongodb.host=localhost



# Show debug logs for Spring Boot startup
logging.level.org.springframework.security=DEBUG
logging.level.com.auth.security=DEBUG
