spring.application.name=customer-service
server.port=8086
spring.main.web-application-type=reactive

# MongoDB local connection
spring.data.mongodb.uri=mongodb://localhost:27017/customer_db
spring.data.mongodb.database=customer_db
spring.data.mongodb.host=mongo
spring.data.mongodb.port=27017


# RabbitMQ local connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Disable Kafka
spring.kafka.bootstrap-servers=disabled
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
# SWAGGER CONFIG
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true
api.info.title=Customer Service API
api.info.version=1.0
api.info.description=Handles customer onboarding and management