spring.application.name=customer-service
server.port=8086
spring.main.web-application-type=reactive

# MongoDB local connection
spring.data.mongodb.uri=mongodb://localhost:27017/customer_db
spring.data.mongodb.database=customer_db
spring.data.mongodb.host=mongo
spring.data.mongodb.port=27017


# RabbitMQ local connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Disable Kafka
spring.kafka.bootstrap-servers=disabled
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
