spring.application.name=account-service
spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=8085
spring.main.web-application-type=reactive
spring.data.mongodb.uri=mongodb://localhost:27017/account_db
spring.data.mongodb.database=account_db
spring.data.mongodb.port=27017
spring.data.mongodb.host=localhost

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.missing-queues-fatal=false

# SWAGGER CONFIG
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true
api.info.title=Account Service API
api.info.version=1.0
api.info.description=Handles account onboarding and management

